name: Daily Commit

on:
  schedule:
    - cron: '05 0 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:

permissions:
  contents: write  # Ensures write access for commits

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Ensures credentials are kept for pushing

      - name: Make a Change (23f2004320@ds.study.iitm.ac.in)
        run: |
          echo "$(date) - Commit from GitHub Actions" >> last_run.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add last_run.txt
          git commit -m "Automated commit - $(date)" || echo "No changes to commit"
          git push
